[package]
name = "rimworld_tools"
version = "0.1.0"
authors = ["isavegas <isavegas2006@gmail.com>"]
description = "Simple tool/library for querying RimWorld mod and game configuration."

[dependencies]
quick-xml = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.3.0"
